version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3336:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    environment:
      - PMA_HOST=mysql-db

  application:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - /app/node_modules
      - uploads:/app/upload
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql-db:3306/${DATABASE_NAME}

volumes:
  mysql-data: {}
  uploads: 